image: trion/ng-cli-karma

stages:
  - test

before_script:
  - npm install

cache:
  paths:
    - node_modules/

angular_tests:
  stage: test
  script:
    - ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - coverage/
  tags:
    - docker
